### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by clair3st** [Firefly4266/portfolio#17]
The idea for a portfolio of images is a really good one!

Unfortunately, when I open the page the images don't show up. There might be something wrong in your links. If you remove this  `/home/jp/codefellows/301/portfolio/` before each of your image tags in the body of your content it should work.

I also recommend making the images the size you want them to appear on the page so the page isn't trying to load such large images. It took me ages to pull this repo onto my computer because it had to pull down so many large images.

I don't see your Nav section when I open the page. And when I inspect it doesn't have any content. I couldn't work it out but it does help to remove the `display: none` from the `.menu` in the `style.css`.

The filters populate great. But they don't display or hide other articles when you select something in them, I think this is because you haven't linked this through a class name (like 'data category') in your `toHtml` function, set a class here as your category and set the category in the `handleProjectFilter` to the same thing so that they are linked.

It might help to organise your js files in a folder to keep track of where all your code is.

I know you had issues during the weeks so getting it to this point is a great accomplishment! congrats and keep going to make it look even better 👍

**Comment by Firefly4266** [comment]
Thanks Claire for the feedback.  I'm working on it, hopefully, I'll have it
all good by Monday.

Regards, John Gaines
